#!/usr/bin/env python

import logging
import sys

import convirt.runtime

def _main():
    runtimes = convirt.runtime.supported()
    if not runtimes:
        logging.warning('no runtimes detected, nothing to do')
        return

    for rt in runtimes:
        print(rt)


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    _main()
